<command> ::= <add_car> | <list_cars> | <find_car> | <remove_car> | <update_car> | <quit>
<add_car> ::= "add_car" <car>
<list_cars> ::= "list_cars"
<find_car> ::= "find_car" <car_id>
<remove_car> ::= "remove_car" <car_id>
<update_car> ::= "update_car" <car>
<car> ::= "Car" <car_id> <model> <year> <color> <fuel_type>
<car_id> ::= <string>
<fuel_type> ::= "Fuel Type:" <string>
<model> ::= "Model:" <string>
<year> ::= "Year:" <integer>
<color> ::= "Color:" <string>
<string> ::= <any sequence of characters>
<integer> ::= <sequence of digits>
<quit> ::= "quit"
